# Generated by Django 4.2.27 on 2026-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='observations',
            field=models.TextField(null=True),
        ),
    ]
