# Generated by Django 4.2.27 on 2026-01-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0002_log_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
    ]
