# Generated by Django 4.2.27 on 2026-01-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0003_remove_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='depart',
            field=models.CharField(default='', max_length=255),
        ),
    ]
