# Generated by Django 4.2.27 on 2026-02-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0007_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
    ]
