# Generated by Django 4.2.27 on 2026-02-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0008_remove_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
    ]
