# Generated by Django 4.2.27 on 2026-02-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0011_logs_delete_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='pilot',
        ),
    ]
