# Generated by Django 4.2.27 on 2026-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0013_logs_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='depart',
            field=models.DateField(verbose_name='depart'),
        ),
    ]
