# Generated by Django 4.2.27 on 2026-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0015_alter_logs_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='depart',
            field=models.DateField(),
        ),
    ]
