# Generated by Django 4.2.27 on 2026-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0016_alter_logs_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='retour',
            field=models.DateField(),
        ),
    ]
