# Generated by Django 4.2.27 on 2026-02-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member_zone', '0017_alter_logs_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='appareil',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='pilot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
