# Generated by Django 4.2.27 on 2026-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_zone', '0018_alter_logs_appareil_alter_logs_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='appareil',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
