# Generated by Django 4.2.27 on 2026-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default=None, upload_to='carte'),
            preserve_default=False,
        ),
    ]
