# Generated by Django 4.2.27 on 2026-01-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
