# Generated by Django 4.2.27 on 2026-01-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_remove_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carte/'),
        ),
    ]
