# Generated by Django 4.2.27 on 2026-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_articles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='carte/')),
            ],
        ),
    ]
