# Generated by Django 4.2.27 on 2026-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/carte/'),
        ),
    ]
