# Generated by Django 4.2.27 on 2026-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_carte_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='img',
        ),
        migrations.AddField(
            model_name='carte',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carte/'),
        ),
    ]
